#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later

set -eu

usage() {
	cat <<'EOF'
Usage: adb-validate.sh [--serial SERIAL] [--remote-path PATH] [--network] <base-url>

Prepare a connected Android device for nix-termux validation by pushing a
Termux-side install-and-smoke script over adb.

Arguments:
  base-url  Release base URL reachable from the Android device.

Options:
  --serial SERIAL     adb serial to use when multiple devices are attached.
  --remote-path PATH  Device path for the script.
                      Defaults to /sdcard/Download/nix-termux-validate.sh.
  --network          Run `nix-termux smoke-test --network` in the script.
  --no-launch        Do not try to bring Termux to the foreground.
EOF
}

die() {
	printf 'adb-validate.sh: %s\n' "$*" >&2
	exit 1
}

shell_quote() {
	printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

serial=
remote_path=/sdcard/Download/nix-termux-validate.sh
network=no
launch=yes

while [ "$#" -gt 0 ]; do
	case $1 in
	--serial)
		[ "$#" -ge 2 ] || die "--serial requires a value"
		[ -n "$2" ] || die "--serial requires a non-empty value"
		serial=$2
		shift 2
		;;
	--remote-path)
		[ "$#" -ge 2 ] || die "--remote-path requires a value"
		[ -n "$2" ] || die "--remote-path requires a non-empty value"
		remote_path=$2
		shift 2
		;;
	--network)
		network=yes
		shift
		;;
	--no-launch)
		launch=no
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	-*)
		usage >&2
		exit 2
		;;
	*)
		break
		;;
	esac
done

[ "$#" -eq 1 ] || {
	usage >&2
	exit 2
}

base_url=$1
[ -n "$base_url" ] || die "base-url must not be empty"
case $base_url in
*[[:space:]]*)
	die "base-url must not contain whitespace"
	;;
esac
case $base_url in
http://* | https://*)
	;;
*)
	die "base-url must start with http:// or https://"
	;;
esac
command -v adb >/dev/null 2>&1 || die "adb is required"

adb_cmd() {
	if [ -n "$serial" ]; then
		adb -s "$serial" "$@"
	else
		adb "$@"
	fi
}

tmp=${TMPDIR:-/tmp}/nix-termux-adb-validate.$$

cleanup() {
	rm -f "$tmp"
}
trap cleanup EXIT INT TERM

smoke_args=
if [ "$network" = yes ]; then
	smoke_args=' --network'
fi

base_url_quoted=$(shell_quote "$base_url")
remote_path_quoted=$(shell_quote "$remote_path")

cat >"$tmp" <<EOF
#!/data/data/com.termux/files/usr/bin/sh
# Generated by nix-termux tools/adb-validate.sh
set -eu

pkg install -y proot curl tar xz coreutils
export NIX_TERMUX_CHANNEL_BASE_URL=$base_url_quoted
tmp_dir=\$(mktemp -d)
trap 'rm -rf "\$tmp_dir"' EXIT INT TERM
curl -fL "\$NIX_TERMUX_CHANNEL_BASE_URL/install.sh" -o "\$tmp_dir/install.sh"
curl -fL "\$NIX_TERMUX_CHANNEL_BASE_URL/install.sh.sha256" -o "\$tmp_dir/install.sh.sha256"
(cd "\$tmp_dir" && sha256sum -c install.sh.sha256)
sh "\$tmp_dir/install.sh"
nix-termux doctor --json
nix-termux smoke-test$smoke_args
EOF

adb_cmd push "$tmp" "$remote_path" >/dev/null
adb_cmd shell chmod 0644 "$remote_path" >/dev/null 2>&1 || true

if [ "$launch" = yes ]; then
	adb_cmd shell monkey -p com.termux 1 >/dev/null 2>&1 || true
fi

cat <<EOF
Pushed validation script to:
  $remote_path

Run this inside stock Termux on the Android device:
  sh $remote_path_quoted
EOF
