name: Nix CI

on:
  push:
    branches:
      - main
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  nix-ci:
    uses: hermetic-foundation/.github/.github/workflows/nix-ci.yml@main
